### ISSUE TITLE
Bring your... brains, I guess. The rest of you would be good too.

### ISSUE THREAD

**Issue by JupiterSayuri451** [Swipefly/INHERENTLY_BROKEN#12]

**Comment by Quintavia** [comment]
Most often interpreted as a comment on the futility of the human body on the grand cosmic scale, this quote holds a hidden, deeper meaning as well. In his introspection and meditation, the Salty One has transcended all temporal boundaries; he lives in many futures simultaneously. Surely there must be one where humans have no need for bodies, and function as floating brains, devoid of spatial movement but rather movement on a higher plane of awareness. Full of Salt as he is, the Salty One is possibly voicing his impatience with our flimsy, decaying flesh vessels, looking forward to a time when our brains will be free from obstinate organs and muscular moorings.
