### ISSUE TITLE
Well, I'm glad I'm not part of "everyone."

### ISSUE THREAD

**Issue by JupiterSayuri451** [Swipefly/INHERENTLY_BROKEN#23]

**Comment by Swipefly** [comment]
Separating yourself from the majority is crucial to being a member of a cult or religion. A true follower of Salt plays the victim card every time they are challenged and loudly expresses outrage at the ridicule of their minority. "Everyone" is wrong, and only Salt and its followers can be correct. If you don't know the right thing to do, pay attention to what educated, intelligent people do, and do the exact opposite.
