### ISSUE TITLE
^ this is exactly what I predicted… and it makes me sad

### ISSUE THREAD

**Issue by JupiterSayuri451** [Swipefly/INHERENTLY_BROKEN#42]

**Comment by Swipefly** [comment]
The Salty One is all-knowing. He can accurately predict any and every decision others will make, and often finds them ridiculous or senseless. Although we may not possess the gift that was bestowed upon him, it doesn't mean that we can't judge others. It is our duty to faithfully judge and criticize others, whether they be right or not in our minds. Criticism causes anger and helps bring more disciples to Salt.
