### ISSUE TITLE
I find this funny

### ISSUE THREAD

**Issue by Swipefly** [Swipefly/INHERENTLY_BROKEN#47]

**Comment by Quintavia** [comment]
The Salty One has no time for laughter. It is a foolish noise, only fit for the mouths of fools. People who say “show, don’t tell”? Fools. Only through the usage of one’s words can emotions be intelligently conveyed. The Salty One states what he is feeling, thus setting an example for us all, and giving us a pearl of wisdom as well; humor is entirely reliant on opinion, so it is incorrect to label something funny without clarifying that not all will find it so. How wise our Prophet! How enlightened is he!
