### ISSUE TITLE
I propose we have a general game day to play various... er, games.

### ISSUE THREAD

**Issue by JupiterSayuri451** [Swipefly/INHERENTLY_BROKEN#9]

**Comment by Swipefly** [comment]
HE INVENTED THE OLYMPICS

**Comment by Swipefly** [comment]
The Olympic Games are the most amazing and widespread sporting event in the world. Unbeknownst to many, these games were actually created by our Salty One. At a meeting with his apostles, he decided to create a "general game day" on which people would flock from all over the world to become angry and compete with each other. The more competitive they got, the angrier they got when they lost, and the closer they grew to Salt. The project was designed to create athletic idols that served Salt. The people would be impressed by these stars and learn to hate everything, just like them. Eventually, the event would expand to be sixteen days long, but the goal of the competition is the same.
